### ISSUE TITLE
[BUG] TerminalInfo.detect_capabilities throws error for Kitty terminal

### ISSUE THREAD

**Issue by cwaldbieser** [GuardKenzie/chafa.py#25]
## What am I doing?
I am trying to detect my terminal's capabilities.  On my kitty terminal, an exception is raised.

## Expected behavior
I expected a TerminalCapabilities object to be returned.  In gnome-terminal 3.44.0, this works as expected.

## To reproduce
Run the script below.
Environment:
```sh
$ kitty --version
kitty 0.27.1 created by Kovid Goyal
$ echo $TERM
xterm-kitty
```

I can provide my `kitty.termcap` or `kitty.terminfo` if required, though these ought to just be whatever the vanilla install provides. 

## Minimum working example

```python
#! /usr/bin/env python

import chafa


def main():
    """
    Main program entrypoint.
    """
    db = chafa.TermDb()
    terminfo = db.detect()
    term_caps = terminfo.detect_capabilities()
    print(term_caps)


if __name__ == "__main__":
    main()
```

## Traceback
Please paste the traceback you got when your program failed over here:

```
Traceback (most recent call last):
  File "/home/waldbiec/git-repos/slack_cli/./t.py", line 17, in <module>
    main()
  File "/home/waldbiec/git-repos/slack_cli/./t.py", line 12, in main
    term_caps = terminfo.detect_capabilities()
  File "/home/waldbiec/git-repos/slack_cli/.venv/lib/python3.10/site-packages/chafa/chafa.py", line 2033, in detect_capabilities
    attributes = get_device_attributes()
  File "/home/waldbiec/git-repos/slack_cli/.venv/lib/python3.10/site-packages/chafa/chafa.py", line 346, in get_device_attributes
    attributes = tuple([int(i) for i in attributes.split(";")])
  File "/home/waldbiec/git-repos/slack_cli/.venv/lib/python3.10/site-packages/chafa/chafa.py", line 346, in <listcomp>
    attributes = tuple([int(i) for i in attributes.split(";")])
ValueError: invalid literal for int() with base 10: ''
```

## System info
Please provide the following details:
- **OS**: Ubuntu 22.04
- **Chafa.py version**: 1.1.0
- **Python version**: 3.10.6

**Comment by GuardKenzie** [comment]
Hihi! Thanks for reporting this. Should be an easy fix; I'll take a closer look later this week, after my vacation.
