### ISSUE TITLE
[FR] Windows support

### ISSUE THREAD

**Issue by ofek** [GuardKenzie/chafa.py#4]
Great work so far!

**Comment by GuardKenzie** [comment]
Hihi!

Windows and MacOS support are currently being worked on. See #5

**Comment by hpjansson** [comment]
I imagine one issue you might run into here is that I'm not publishing Chafa DLLs for Windows. That's easily fixed, though -- one of the things I did in the 1.12 series was enabling Windows DLL builds, so I can just start publishing those.

I'm unsure if that's needed though, or if Windows users are already getting DLLs from their package managers. @ofek do you know?

**Comment by GuardKenzie** [comment]
When I was testing this, I got it working by installing chafa through msys. 

The only thing there is that users need to add something like `C:\msys2\mingw64\bin` to their `%PATH%` so that chafa.py can find thee library.

**Comment by ofek** [comment]
Windows package management is quite different compared to Linux & macOS, users would expect the wheel to ship with everything necessary included

**Comment by hpjansson** [comment]
> The only thing there is that users need to add something like C:\msys2\mingw64\bin to their %PATH% so that chafa.py can find the library.

Ah, no problem then. I know there are a few distribution mechanisms (another one I've seen people use is Scoop), but I don't have a good overview. I usually go with MSYS too, but mostly just cross-compile and cross my fingers.

**Comment by GuardKenzie** [comment]
> Windows package management is quite different compared to Linux & macOS, users would expect the wheel to ship with everything necessary included

Ah I see. Thanks for letting me know! I'll get to work on this as soon as I have time (hopefully next week)

**Comment by ofek** [comment]
Thanks! Just FYI it looks like the job to release the wheels was skipped

**Comment by GuardKenzie** [comment]
Yeah, I know. I think I might just upload them manually to PyPi and hope it works next time hehe

**Comment by GuardKenzie** [comment]
@ofek Wheels are up on PyPi!
